#!/usr/bin/env bash
set -euo pipefail

# Description: Generate a project-specific Agents.md from modular guidance
# Usage: seed.sh --language=<lang> [--type=<type>] [--path=<path>]
#
# Examples:
#   seed.sh --language=javascript --type=genesis-tools --path=./my-project
#   seed.sh --language=python --path=./my-project
#   seed.sh --language=go,shell --type=cli-tools

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GUIDANCE_DIR="$SCRIPT_DIR"

# Defaults
LANGUAGES=""
PROJECT_TYPE=""
OUTPUT_PATH="."
PROJECT_NAME=""
COMPACT=false
DRY_RUN=false

usage() {
    cat << EOF
Usage: ${0##*/} [OPTIONS]

Generate a project-specific Agents.md from modular guidance.

Options:
    --language=LANG     Languages to include (comma-separated: go,python,javascript,shell,dart-flutter)
    --type=TYPE         Project type (genesis-tools, cli-tools, web-apps, mobile-apps)
    --path=PATH         Output directory (default: current directory)
    --name=NAME         Project name for header (default: directory name)
    --compact           Generate compact version (~100 lines) instead of full
    --dry-run           Print what would be generated without writing
    -h, --help          Show this help message

Available Languages:
    go, python, javascript, shell, dart-flutter

Available Project Types:
    genesis-tools, cli-tools, web-apps, mobile-apps

Examples:
    ${0##*/} --language=javascript --type=genesis-tools --path=./my-project
    ${0##*/} --language=dart-flutter --type=mobile-apps --path=./my-flutter-app
    ${0##*/} --language=go,shell --type=cli-tools --compact --dry-run
EOF
}

# Parse arguments
for arg in "$@"; do
    case $arg in
        --language=*)
            LANGUAGES="${arg#*=}"
            ;;
        --type=*)
            PROJECT_TYPE="${arg#*=}"
            ;;
        --path=*)
            OUTPUT_PATH="${arg#*=}"
            ;;
        --name=*)
            PROJECT_NAME="${arg#*=}"
            ;;
        --compact)
            COMPACT=true
            ;;
        --dry-run)
            DRY_RUN=true
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $arg" >&2
            usage
            exit 1
            ;;
    esac
done

# Set project name from directory if not specified
if [[ -z "$PROJECT_NAME" ]]; then
    PROJECT_NAME=$(basename "$(cd "$OUTPUT_PATH" 2>/dev/null && pwd)" 2>/dev/null || echo "Project")
fi

# Validate
if [[ -z "$LANGUAGES" ]]; then
    echo "Error: --language is required" >&2
    usage
    exit 1
fi

# Get language-specific commands
get_lang_commands() {
    local lang="$1"
    case "$lang" in
        go)
            echo "LINT:golangci-lint run ./..."
            echo "BUILD:go build ./..."
            echo "TEST:go test -race -coverprofile=coverage.out ./..."
            echo "COVERAGE:80"
            ;;
        python)
            echo "LINT:pylint --fail-under=9.5 ."
            echo "BUILD:mypy ."
            echo "TEST:pytest --cov=. --cov-report=term-missing"
            echo "COVERAGE:80"
            ;;
        javascript)
            echo "LINT:npm run lint"
            echo "BUILD:npm run build"
            echo "TEST:npm test"
            echo "COVERAGE:70"
            ;;
        dart-flutter)
            echo "LINT:flutter analyze"
            echo "BUILD:flutter build"
            echo "TEST:flutter test --coverage"
            echo "COVERAGE:70"
            ;;
        shell)
            echo "LINT:shellcheck *.sh"
            echo "BUILD:bash -n *.sh"
            echo "TEST:bats test/"
            echo "COVERAGE:N/A"
            ;;
        *)
            echo "LINT:# Add lint command"
            echo "BUILD:# Add build command"
            echo "TEST:# Add test command"
            echo "COVERAGE:70"
            ;;
    esac
}

# Generate compact Agents.md (~200-300 lines)
generate_compact_agents_md() {
    local today
    today=$(date +%Y-%m-%d)

    # Get commands from first language
    IFS=',' read -ra LANG_ARRAY <<< "$LANGUAGES"
    local first_lang="${LANG_ARRAY[0]}"
    local lint_cmd build_cmd test_cmd coverage

    while IFS= read -r line; do
        case "$line" in
            LINT:*) lint_cmd="${line#LINT:}" ;;
            BUILD:*) build_cmd="${line#BUILD:}" ;;
            TEST:*) test_cmd="${line#TEST:}" ;;
            COVERAGE:*) coverage="${line#COVERAGE:}" ;;
        esac
    done < <(get_lang_commands "$first_lang")

    cat << COMPACT_HEADER
# AI Agent Guidelines - $PROJECT_NAME

> **Generated by**: superpowers-plus/guidance/seed.sh (compact mode)
> **Last Updated**: $today
> **Languages**: $LANGUAGES
> **Type**: ${PROJECT_TYPE:-general}

Self-contained. Minimal high-signal tokens. See full guidance modules for details.

---

## Superpowers Integration

At the START of every conversation, run:

\`\`\`bash
node ~/.codex/superpowers-augment/superpowers-augment.js bootstrap
\`\`\`

### Key Skills

| Skill | When to Invoke |
|-------|---------------|
| \`superpowers:brainstorming\` | Before creative/feature work |
| \`superpowers:systematic-debugging\` | Before fixing bugs |
| \`superpowers:test-driven-development\` | Before writing implementation |
| \`superpowers:verification-before-completion\` | Before claiming done |
| \`superpowers:writing-plans\` | Before multi-step tasks |

**The Rule**: IF A SKILL APPLIES (even 1% chance), YOU MUST INVOKE IT.

---

## Communication Standards

- **No flattery** - Skip "Great question!" or "Excellent point!"
- **No hype words** - Avoid "revolutionary", "game-changing", "cutting-edge"
- **Evidence-based** - Cite sources, provide data, or qualify as opinion
- **Direct** - State facts without embellishment

### Banned Phrases

| Category | Avoid |
|----------|-------|
| Self-Promotion | production-grade, world-class, enterprise-ready |
| Filler | incredibly, extremely, very, really, truly |
| AI Tells | leverage, utilize, facilitate, streamline, optimize |
| Sycophancy | Happy to help!, Absolutely!, I appreciate... |

---

## Quality Gates

### Before Committing

1. **Lint**: \`$lint_cmd\`
2. **Build**: \`$build_cmd\`
3. **Test**: \`$test_cmd\`
4. **Coverage**: Minimum ${coverage}%

### Before Pushing

- [ ] All tests pass
- [ ] No linting errors
- [ ] No secrets in code
- [ ] Commit messages are descriptive

### Before Deploying

- [ ] CI shows green checkmark
- [ ] Security scan passed
- [ ] Documentation updated

COMPACT_HEADER

    # Add essential language rules (condensed)
    echo "---"
    echo ""
    echo "## Language Quick Reference"
    echo ""

    for lang in "${LANG_ARRAY[@]}"; do
        case "$lang" in
            go)
                cat << 'GO_RULES'
### Go

- Run `golangci-lint run ./...` then `go build ./...` before committing
- 80% test coverage minimum with table-driven tests
- Error handling: wrap with context, no naked returns
- Use `context.Context` for cancellation/timeouts

GO_RULES
                ;;
            python)
                cat << 'PYTHON_RULES'
### Python

- Type annotations required on all public functions
- pylint score ≥9.5, mypy strict mode
- Use dataclasses for DTOs, Pydantic for validation
- Virtual environments mandatory

PYTHON_RULES
                ;;
            javascript)
                cat << 'JS_RULES'
### JavaScript

- ESLint + Prettier, 2-space indent
- Prefer TypeScript for new code
- async/await over callbacks
- No console.log in production code

JS_RULES
                ;;
            dart-flutter)
                cat << 'DART_RULES'
### Dart/Flutter

- `flutter analyze` must pass with zero issues
- Use AppLogger for structured logging (never print())
- StatefulWidget only when State is truly needed
- Riverpod/Provider for state management

DART_RULES
                ;;
            shell)
                cat << 'SHELL_RULES'
### Shell

- Start with `set -euo pipefail`
- shellcheck must pass
- Use BSD-compatible flags for macOS
- Quote all variables: "$var"

SHELL_RULES
                ;;
        esac
    done

    # Add project type essentials if specified
    if [[ -n "$PROJECT_TYPE" ]]; then
        echo "---"
        echo ""
        echo "## Project Type: ${PROJECT_TYPE}"
        echo ""

        case "$PROJECT_TYPE" in
            cli-tools)
                cat << 'CLI_RULES'
- Provide --help, --version, --quiet, --verbose flags
- Exit codes: 0=success, 1=error, 2=usage error
- Support stdin/stdout piping
- Colored output with --no-color option

CLI_RULES
                ;;
            web-apps)
                cat << 'WEB_RULES'
- Never commit secrets, use environment variables
- API versioning: /api/v1/...
- Health check endpoint required: /health
- CORS, rate limiting, input validation

WEB_RULES
                ;;
            mobile-apps)
                cat << 'MOBILE_RULES'
- iOS: 180s build timeout, `pod install` before build
- Android: 300s build timeout, verify keystore
- Use structured logging with privacy controls
- Test on both platforms before merging

MOBILE_RULES
                ;;
            genesis-tools)
                cat << 'GENESIS_RULES'
- Follow template structure in genesis/templates/
- Validate all user inputs before processing
- Include usage examples in generated output
- Support --dry-run for previewing

GENESIS_RULES
                ;;
        esac
    fi

    cat << COMPACT_FOOTER

---

## Context Management

- **Context rot**: Model accuracy degrades as context fills. Keep tokens high-signal.
- **Progressive disclosure**: Load Agents.md always, modules on-demand, code just-in-time.
- **Compact at 75%**: Summarize history, keep decisions, drop exploration.
- **Session resume**: Check \`git log -5\`, \`git status\`, load notes before proceeding.

---

## Project-Specific Rules

<!-- Add project-specific guidance below -->

---

## Quick Commands

\`\`\`bash
# Lint
$lint_cmd

# Build
$build_cmd

# Test
$test_cmd
\`\`\`

---

*For detailed guidance, see: superpowers-plus/guidance/*
COMPACT_FOOTER
}

# Build the full Agents.md content
generate_agents_md() {
    local today
    today=$(date +%Y-%m-%d)

    cat << HEADER
# AI Agent Guidelines - $PROJECT_NAME

> **Generated by**: superpowers-plus/guidance/seed.sh
> **Last Updated**: $today
> **Languages**: $LANGUAGES
> **Type**: ${PROJECT_TYPE:-general}

This file is self-contained and portable. No external references required.

---

HEADER

    # Always include core guidance
    echo "## Core Guidelines"
    echo ""
    cat "$GUIDANCE_DIR/core/superpowers.md"
    echo ""
    echo "---"
    echo ""
    cat "$GUIDANCE_DIR/core/communication.md"
    echo ""
    echo "---"
    echo ""
    cat "$GUIDANCE_DIR/core/anti-slop.md"
    echo ""
    echo "---"
    echo ""

    # Include workflow guidance
    echo "## Workflows"
    echo ""
    cat "$GUIDANCE_DIR/workflows/deployment.md"
    echo ""
    echo "---"
    echo ""
    cat "$GUIDANCE_DIR/workflows/testing.md"
    echo ""
    echo "---"
    echo ""
    cat "$GUIDANCE_DIR/workflows/security.md"
    echo ""
    echo "---"
    echo ""
    cat "$GUIDANCE_DIR/workflows/build-hygiene.md"
    echo ""
    echo "---"
    echo ""
    cat "$GUIDANCE_DIR/workflows/context-management.md"
    echo ""

    # Include language-specific guidance
    echo "---"
    echo ""
    echo "## Language-Specific Guidelines"
    echo ""

    IFS=',' read -ra LANG_ARRAY <<< "$LANGUAGES"
    for lang in "${LANG_ARRAY[@]}"; do
        lang_file="$GUIDANCE_DIR/languages/${lang}.md"
        if [[ -f "$lang_file" ]]; then
            cat "$lang_file"
            echo ""
            echo "---"
            echo ""
        else
            echo "Warning: No guidance file for language: $lang" >&2
        fi
    done

    # Include project type guidance if specified
    if [[ -n "$PROJECT_TYPE" ]]; then
        type_file="$GUIDANCE_DIR/project-types/${PROJECT_TYPE}.md"
        if [[ -f "$type_file" ]]; then
            echo "## Project Type Guidelines"
            echo ""
            cat "$type_file"
            echo ""
        else
            echo "Warning: No guidance file for project type: $PROJECT_TYPE" >&2
        fi
    fi

    # Footer with project-specific section
    cat << FOOTER

---

## Project-Specific Rules

<!-- Add project-specific guidance below -->

FOOTER
}

# Select generator based on mode
if [[ "$COMPACT" == "true" ]]; then
    generator="generate_compact_agents_md"
    mode_label="compact"
else
    generator="generate_agents_md"
    mode_label="full"
fi

# Output
if [[ "$DRY_RUN" == "true" ]]; then
    echo "=== DRY RUN ($mode_label mode): Would generate the following Agents.md ==="
    echo ""
    $generator
else
    mkdir -p "$OUTPUT_PATH"
    output_file="$OUTPUT_PATH/Agents.md"
    $generator > "$output_file"
    echo "Generated ($mode_label): $output_file"
    echo "Lines: $(wc -l < "$output_file")"
fi

