#!/bin/bash
# migrate-agents.sh - Migrate existing Agents.md to Golden Agents format
# Preserves all repo-specific content while adding missing critical sections
#
# Usage: ./migrate-agents.sh --repo=<path> [--dry-run] [--language=<lang>] [--type=<type>]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRY_RUN=false
REPO_PATH=""
LANGUAGE="shell"
TYPE="cli-tools"

# Parse arguments
for arg in "$@"; do
  case $arg in
    --repo=*) REPO_PATH="${arg#*=}" ;;
    --language=*) LANGUAGE="${arg#*=}" ;;
    --type=*) TYPE="${arg#*=}" ;;
    --dry-run) DRY_RUN=true ;;
    --help) 
      echo "Usage: $0 --repo=<path> [--language=<lang>] [--type=<type>] [--dry-run]"
      exit 0
      ;;
  esac
done

if [ -z "$REPO_PATH" ]; then
  echo "Error: --repo=<path> is required"
  exit 1
fi

# Find existing Agents.md
EXISTING_FILE=""
if [ -f "$REPO_PATH/Agents.md" ]; then
  EXISTING_FILE="$REPO_PATH/Agents.md"
elif [ -f "$REPO_PATH/AGENTS.md" ]; then
  EXISTING_FILE="$REPO_PATH/AGENTS.md"
fi

# Generate the Golden Agents header (compact mode)
generate_header() {
  cat << 'HEADER'
# AI Agent Guidelines

> **Auto-generated by Golden Agents Framework** | [superpowers-plus/guidance](https://github.com/bordenet/superpowers-plus)

---

## Superpowers Bootstrap

At the START of every conversation, run:

```bash
node ~/.codex/superpowers-augment/superpowers-augment.js bootstrap
```

**Key skills to invoke:**
| Skill | When to Use |
|-------|-------------|
| `superpowers:brainstorming` | Before creative/feature work |
| `superpowers:systematic-debugging` | Before fixing bugs |
| `superpowers:test-driven-development` | Before writing implementation |
| `superpowers:verification-before-completion` | Before claiming done |

---

## Communication Standards

### Banned Phrases
| AI Tells | leverage, utilize, facilitate, streamline, optimize |
| Filler | It's important to note, It's worth mentioning, Interestingly |
| Sycophancy | Great question!, Happy to help!, Excellent point! |

### Evidence-Based Claims
Every claim requires evidence. No unsubstantiated assertions.

---

## Quality Gates

**Before ANY commit:**
HEADER

  # Add language-specific quality gates
  case "$LANGUAGE" in
    go)
      echo '```bash'
      echo 'golangci-lint run ./...'
      echo 'go test ./... -race -coverprofile=coverage.out'
      echo 'go build ./...'
      echo '```'
      ;;
    python)
      echo '```bash'
      echo 'ruff check . && ruff format --check .'
      echo 'pytest --cov=. --cov-fail-under=80'
      echo 'mypy . --strict'
      echo '```'
      ;;
    javascript)
      echo '```bash'
      echo 'npm run lint'
      echo 'npm test'
      echo 'npm run build'
      echo '```'
      ;;
    shell)
      echo '```bash'
      echo 'shellcheck *.sh'
      echo 'bash -n *.sh'
      echo '```'
      ;;
    dart-flutter)
      echo '```bash'
      echo 'flutter analyze'
      echo 'flutter test --coverage'
      echo 'dart format --set-exit-if-changed .'
      echo '```'
      ;;
  esac

  cat << 'CONTEXT'

---

## Context Management

- **Context rot**: Model accuracy degrades as context fills. Keep tokens high-signal.
- **Progressive disclosure**: Load Agents.md always, modules on-demand, code just-in-time.
- **At 75% context**: Summarize conversation history, drop low-value context.
- **Session resumption**: Check `git status`, `git log -5`, load notes before proceeding.

---

CONTEXT
}

# Main migration logic
if [ -n "$EXISTING_FILE" ]; then
  echo "=== Migrating: $EXISTING_FILE ==="
  echo "Language: $LANGUAGE, Type: $TYPE"
  echo ""
  
  # Check if already has superpowers bootstrap
  HAS_SUPERPOWERS=$(grep -c "superpowers-augment" "$EXISTING_FILE" 2>/dev/null | tr -d '\n' || echo "0")
  HAS_BANNED=$(grep -c "Banned Phrases" "$EXISTING_FILE" 2>/dev/null | tr -d '\n' || echo "0")
  HAS_CONTEXT=$(grep -c "Context Management" "$EXISTING_FILE" 2>/dev/null | tr -d '\n' || echo "0")

  echo "Current coverage:"
  echo "  Superpowers bootstrap: $([ "${HAS_SUPERPOWERS:-0}" -gt 0 ] && echo "YES" || echo "NO")"
  echo "  Banned phrases: $([ "${HAS_BANNED:-0}" -gt 0 ] && echo "YES" || echo "NO")"
  echo "  Context management: $([ "${HAS_CONTEXT:-0}" -gt 0 ] && echo "YES" || echo "NO")"
  echo ""
  
  if [ "$DRY_RUN" = true ]; then
    echo "[DRY RUN] Would generate migrated file with:"
    echo "  - Golden Agents header (superpowers, banned phrases, context mgmt)"
    echo "  - All existing repo-specific content preserved"
    echo ""
    echo "--- HEADER PREVIEW ---"
    generate_header | head -40
    echo "..."
    echo ""
    echo "--- EXISTING CONTENT (first 20 lines) ---"
    head -20 "$EXISTING_FILE"
  else
    # Create backup
    cp "$EXISTING_FILE" "${EXISTING_FILE}.backup"
    echo "Backup created: ${EXISTING_FILE}.backup"
    
    # Generate new file
    TEMP_FILE=$(mktemp)
    generate_header > "$TEMP_FILE"
    echo "## Project-Specific Guidelines" >> "$TEMP_FILE"
    echo "" >> "$TEMP_FILE"
    cat "$EXISTING_FILE" >> "$TEMP_FILE"
    
    mv "$TEMP_FILE" "$EXISTING_FILE"
    echo "Migration complete: $EXISTING_FILE"
  fi
else
  echo "No existing Agents.md found in $REPO_PATH"
  echo "Use seed.sh to generate a new one instead."
fi

