#!/usr/bin/env bash
set -euo pipefail

# Description: Generate a project-specific Agents.md from modular guidance
# Usage: seed.sh --language=<lang> [--type=<type>] [--path=<path>]
#
# Examples:
#   seed.sh --language=javascript --type=genesis-tools --path=./my-project
#   seed.sh --language=python --path=./my-project
#   seed.sh --language=go,shell --type=cli-tools

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GUIDANCE_DIR="$SCRIPT_DIR"

# Defaults
LANGUAGES=""
PROJECT_TYPE=""
OUTPUT_PATH="."
DRY_RUN=false

usage() {
    cat << EOF
Usage: ${0##*/} [OPTIONS]

Generate a project-specific Agents.md from modular guidance.

Options:
    --language=LANG     Languages to include (comma-separated: go,python,javascript,shell)
    --type=TYPE         Project type (genesis-tools, cli-tools, web-apps)
    --path=PATH         Output directory (default: current directory)
    --dry-run           Print what would be generated without writing
    -h, --help          Show this help message

Examples:
    ${0##*/} --language=javascript --type=genesis-tools --path=./my-project
    ${0##*/} --language=python --path=./my-project
    ${0##*/} --language=go,shell --type=cli-tools --dry-run
EOF
}

# Parse arguments
for arg in "$@"; do
    case $arg in
        --language=*)
            LANGUAGES="${arg#*=}"
            ;;
        --type=*)
            PROJECT_TYPE="${arg#*=}"
            ;;
        --path=*)
            OUTPUT_PATH="${arg#*=}"
            ;;
        --dry-run)
            DRY_RUN=true
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $arg" >&2
            usage
            exit 1
            ;;
    esac
done

# Validate
if [[ -z "$LANGUAGES" ]]; then
    echo "Error: --language is required" >&2
    usage
    exit 1
fi

# Build the Agents.md content
generate_agents_md() {
    local today
    today=$(date +%Y-%m-%d)

    cat << HEADER
# AI Agent Guidelines

> **Generated by**: superpowers-plus/guidance/seed.sh
> **Last Updated**: $today

This file provides AI coding assistants with project-specific guidance.

---

HEADER

    # Always include core guidance
    echo "## Core Guidelines"
    echo ""
    echo "The following core guidelines always apply:"
    echo ""
    cat "$GUIDANCE_DIR/core/superpowers.md"
    echo ""
    echo "---"
    echo ""
    cat "$GUIDANCE_DIR/core/communication.md"
    echo ""
    echo "---"
    echo ""
    cat "$GUIDANCE_DIR/core/anti-slop.md"
    echo ""
    echo "---"
    echo ""

    # Include workflow guidance
    echo "## Workflows"
    echo ""
    cat "$GUIDANCE_DIR/workflows/deployment.md"
    echo ""
    echo "---"
    echo ""
    cat "$GUIDANCE_DIR/workflows/testing.md"
    echo ""
    echo "---"
    echo ""
    cat "$GUIDANCE_DIR/workflows/security.md"
    echo ""

    # Include language-specific guidance
    echo "---"
    echo ""
    echo "## Language-Specific Guidelines"
    echo ""
    
    IFS=',' read -ra LANG_ARRAY <<< "$LANGUAGES"
    for lang in "${LANG_ARRAY[@]}"; do
        lang_file="$GUIDANCE_DIR/languages/${lang}.md"
        if [[ -f "$lang_file" ]]; then
            cat "$lang_file"
            echo ""
            echo "---"
            echo ""
        else
            echo "Warning: No guidance file for language: $lang" >&2
        fi
    done

    # Include project type guidance if specified
    if [[ -n "$PROJECT_TYPE" ]]; then
        type_file="$GUIDANCE_DIR/project-types/${PROJECT_TYPE}.md"
        if [[ -f "$type_file" ]]; then
            echo "## Project Type Guidelines"
            echo ""
            cat "$type_file"
            echo ""
        else
            echo "Warning: No guidance file for project type: $PROJECT_TYPE" >&2
        fi
    fi
}

# Output
if [[ "$DRY_RUN" == "true" ]]; then
    echo "=== DRY RUN: Would generate the following Agents.md ==="
    echo ""
    generate_agents_md
else
    mkdir -p "$OUTPUT_PATH"
    output_file="$OUTPUT_PATH/Agents.md"
    generate_agents_md > "$output_file"
    echo "Generated: $output_file"
    echo "Lines: $(wc -l < "$output_file")"
fi

