#!/usr/bin/env bash
# pre-compact-context-ferry.sh -- PreCompact hook for the context-ferry skill.
# Fires before Claude Code context compaction. Generates a rich, standalone
# ferry scaffold so that even if compaction fires mid-model-response, the file
# already contains all objective context (git state, branch, recent commits,
# active CLAUDE.md, session metadata). The model's only job is to append
# Key Decisions + Pending Questions -- a short annotation, not a full write.
#
# This is the backstop. The early-warning hook (user-prompt-submit-context-ferry.sh)
# fires at turn ~20 with enough context remaining to run the full skill.
# This hook fires at ~95% and ensures something useful exists regardless.
#
# Exit: always 0 (never blocks compaction).
set -euo pipefail
if [[ "${CLAUDE_HOOKS_BYPASS:-0}" == "1" ]]; then exit 0; fi

TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OUTFILE="$HOME/context-ferry-${TIMESTAMP}.md"
CWD="${PWD}"
SESSION_ID=""

INPUT="$(cat)"
if command -v jq &>/dev/null; then
    _cwd="$(jq -r '.cwd        // empty' <<<"$INPUT" 2>/dev/null || true)"
    _sid="$(jq -r '.session_id // empty' <<<"$INPUT" 2>/dev/null || true)"
    [[ -n "$_cwd" ]] && CWD="$_cwd"
    [[ -n "$_sid" ]] && SESSION_ID="$_sid"
fi

# ── Write rich scaffold file ──────────────────────────────────────────────────
{
    printf '## CONTEXT FERRY -- %s\n' "$TIMESTAMP"
    printf '_Generated by PreCompact hook. Paste into a fresh session to resume._\n'
    printf '_Fidelity: degraded (generated at PreCompact -- verify Key Files with git/file reads)_\n\n'
    [[ -n "$SESSION_ID" ]] && printf 'Session: %s\n' "$SESSION_ID"
    printf 'Working directory: %s\n\n' "$CWD"
    printf '---\n\n'

    # ── Git context ───────────────────────────────────────────────────────────
    if git -C "$CWD" rev-parse --is-inside-work-tree &>/dev/null 2>&1; then
        BRANCH="$(git -C "$CWD" rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')"
        REMOTE_URL="$(git -C "$CWD" remote get-url origin 2>/dev/null || echo 'none')"

        printf '### Repository\n'
        # shellcheck disable=SC2016
        printf '- Branch: `%s`\n' "$BRANCH"
        printf '- Remote: %s\n\n' "$REMOTE_URL"

        printf '### Recent Commits\n'
        printf '```\n'
        git -C "$CWD" log --oneline -10 2>/dev/null || true
        printf '```\n\n'

        printf '### Working Tree Status\n'
        printf '```\n'
        git -C "$CWD" status --short 2>/dev/null | head -40 || true
        printf '```\n\n'

        DIFF_STAT="$(git -C "$CWD" diff --stat HEAD 2>/dev/null | head -30 || true)"
        if [[ -n "$DIFF_STAT" ]]; then
            printf '### Uncommitted Changes\n'
            # shellcheck disable=SC2016
            printf '```\n%s\n```\n\n' "$DIFF_STAT"
        fi

        UNPUSHED="$(git -C "$CWD" log --oneline '@{u}..HEAD' 2>/dev/null | head -10 || true)"
        if [[ -n "$UNPUSHED" ]]; then
            printf '### Unpushed Commits\n'
            # shellcheck disable=SC2016
            printf '```\n%s\n```\n\n' "$UNPUSHED"
        fi
    else
        printf '### Repository\n_No git repository at %s._\n\n' "$CWD"
    fi

    # ── CLAUDE.md excerpt ─────────────────────────────────────────────────────
    _find_claude_md() {
        local dir="$1"
        while [[ "$dir" != "/" ]]; do
            [[ -f "$dir/CLAUDE.md" ]] && { echo "$dir/CLAUDE.md"; return 0; }
            dir="$(dirname "$dir")"
        done
        return 1
    }
    CLAUDE_MD=""
    CLAUDE_MD="$(_find_claude_md "$CWD")" 2>/dev/null || true
    if [[ -n "$CLAUDE_MD" ]]; then
        printf '### CLAUDE.md (top 30 lines)\n'
        printf '_Source: %s_\n' "$CLAUDE_MD"
        printf '```\n'
        head -30 "$CLAUDE_MD" 2>/dev/null || true
        printf '```\n\n'
    fi

    # ── Model annotation section (filled in by Claude) ────────────────────────
    printf '---\n\n'
    printf '### Key Decisions Made\n'
    printf '_TODO: Claude appends 3-5 bullet points before compaction fires._\n\n'
    printf '### Pending Questions for You\n'
    printf '_TODO: Claude appends unanswered questions verbatim._\n\n'
    printf '### Next 3 Actions\n'
    printf '_TODO: Claude appends the next 3 concrete actions._\n'

} > "$OUTFILE" 2>/dev/null || true

# ── Instruct the model ────────────────────────────────────────────────────────
cat <<MSG
[context-ferry] PreCompact hook fired. Rich scaffold written to: ${OUTFILE}

The scaffold already contains: branch, recent commits, working tree status,
unpushed commits, and CLAUDE.md excerpt.

** YOUR ONLY JOB: open ${OUTFILE} and append to the three TODO sections:
   1. Key Decisions Made (3-5 bullets)
   2. Pending Questions for You (verbatim unanswered questions)
   3. Next 3 Actions

Do NOT re-run the full context-ferry skill. Append only. Keep each section
under 10 lines. Compaction is imminent -- be brief. **
MSG

exit 0
