#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Script: try-sentinel-fast-forward.sh
# PURPOSE: Re-stamp an existing valid .code-review-cleared/.phr-cleared
#          sentinel to the current HEAD SHA, WITHOUT re-dispatching the full
#          AI review, but ONLY when every file changed since the sentinel's
#          SHA is proven -- by actually re-running its deterministic
#          generator command and diffing the output byte-for-byte -- to be
#          exactly what that generator produces. Never trusts a path
#          allowlist alone.
#
#          A first design of this (path-allowlist only, no content check)
#          was REJECTed by progressive-harsh-review for two reasons this
#          version fixes:
#            1. It proposed a 6th sentinel field (fast-forward-from=SHA),
#               which tools/pre-push's own field-count validators reject
#               outright (PHR sentinel requires EXACTLY 5 fields; code-review
#               sentinel accepts 4-5). This version re-stamps the SAME 5
#               fields (SHA + TIMESTAMP updated, VERDICT + min-score carried
#               over unchanged) -- no format change, so nothing new for the
#               validators to reject. The audit trail lives in a separate
#               plain-text log (see FASTFORWARD_LOG below), not the sentinel.
#            2. Path-only allowlisting can't tell "this golden file was
#               regenerated by the real tool" from "this golden file was
#               hand-edited to match an already-broken implementation" --
#               exactly the failure mode code review exists to catch. A
#               second cut of this fix (whole-tree `git status` cleanliness
#               after running the registered generators) was ALSO insufficient:
#               a file matching a registry prefix that its generator doesn't
#               actually write (e.g. a hardcoded internal list the generator
#               never updated for a new file) trivially "reproduces" itself,
#               since nothing touched it. This version proves per-FILE
#               provenance: each matched file is deleted before its generator
#               runs, forcing the generator to prove it actually recreates
#               that exact file's committed bytes -- a file the generator
#               doesn't own stays missing/wrong and is caught. The whole-tree
#               check still runs afterward too, to catch side effects outside
#               the expected file set.
#
# USAGE:   tools/try-sentinel-fast-forward.sh --code-review | --phr
# EXIT:    0 = sentinel fast-forwarded (or already valid for HEAD -- no-op)
#          1 = fast-forward not safe; run the full review instead
#          2 = usage/precondition error (dirty tree, no sentinel, etc.)
# -----------------------------------------------------------------------------
set -euo pipefail

# Resolve from the CALLER's cwd, not this script's own location -- a git
# pre-push hook runs with the working tree as its cwd, and using -C on this
# script's own directory would resolve to the wrong worktree under `git
# worktree` (this script's file lives in exactly one worktree; the caller
# may be pushing from a different one). Fall back to the script's own
# location only when not invoked from inside any repo.
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [[ -z "$REPO_ROOT" ]]; then
    REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
cd "$REPO_ROOT"

FASTFORWARD_LOG="$REPO_ROOT/.cr-battery-runs/fast-forward.log"

# Registry: path PREFIX (relative to repo root) -> deterministic regeneration
# command. Lives in a separate sourced file (tools/lib/fast-forward-registry.sh)
# rather than inline here so tests can point FASTFORWARD_REGISTRY at an
# isolated fixture registry instead of needing a full copy of this repo's
# real generators (test/compress.test.js, etc.) in every test fixture.
FASTFORWARD_REGISTRY="${FASTFORWARD_REGISTRY:-$REPO_ROOT/tools/lib/fast-forward-registry.sh}"
if [[ ! -f "$FASTFORWARD_REGISTRY" ]]; then
    echo "ERROR: registry file not found: $FASTFORWARD_REGISTRY" >&2
    exit 2
fi
# shellcheck source=tools/lib/fast-forward-registry.sh
source "$FASTFORWARD_REGISTRY"

SENTINEL=""
case "${1:-}" in
    --code-review) SENTINEL="$REPO_ROOT/.code-review-cleared" ;;
    --phr)         SENTINEL="$REPO_ROOT/.phr-cleared" ;;
    *)
        echo "Usage: $0 --code-review | --phr" >&2
        exit 2
        ;;
esac

if [[ ! -f "$SENTINEL" ]]; then
    echo "ERROR: $(basename "$SENTINEL") does not exist -- nothing to fast-forward. Run the full review." >&2
    exit 2
fi

# Precondition: working tree must be clean. Otherwise we can't tell "the
# generator produced a mismatch" from "there was already uncommitted stuff
# lying around" when we check git status after running generators below.
if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
    echo "ERROR: working tree is not clean. Commit or stash first, then retry." >&2
    exit 2
fi

sentinel_line="$(head -n1 "$SENTINEL")"
# shellcheck disable=SC2034  # sen_ts is a positional placeholder; timestamp isn't read further
IFS='|' read -r sen_ver sen_sha sen_verdict sen_ts sen_min <<< "$sentinel_line"
if [[ "$sen_ver" != "v1" ]] || [[ -z "$sen_sha" ]] || [[ -z "$sen_verdict" ]]; then
    echo "ERROR: $(basename "$SENTINEL") format unrecognized. Run the full review." >&2
    exit 2
fi

head_sha="$(git rev-parse HEAD)"
if [[ "$sen_sha" == "$head_sha" ]]; then
    echo "✓ $(basename "$SENTINEL") is already valid for HEAD ($head_sha). Nothing to do."
    exit 0
fi

if ! git merge-base --is-ancestor "$sen_sha" HEAD 2>/dev/null; then
    echo "ERROR: sentinel SHA ${sen_sha:0:8} is not an ancestor of HEAD ($head_sha) -- different branch or history rewrite. Run the full review." >&2
    exit 1
fi

changed_files="$(git diff --name-only "$sen_sha" HEAD)"
if [[ -z "$changed_files" ]]; then
    echo "ERROR: no files changed between ${sen_sha:0:8} and HEAD, but SHAs differ (empty commits?). Run the full review to be safe." >&2
    exit 1
fi

echo "Checking ${sen_sha:0:8}..${head_sha:0:8} against the fast-forward generator registry:"
declare -A file_to_generator=()
declare -A needed_generators=()
while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    matched=0
    for prefix in "${!FASTFORWARD_GENERATORS[@]}"; do
        # Directory-prefix entries (registry key ends in "/") match any file
        # under that directory. Exact-file entries (no trailing "/") must
        # match the full path -- a plain prefix test here would let
        # "test/ei-baseline.json" (registry) wrongly match a sibling file
        # like "test/ei-baseline.json.bak" that was never proven regenerable.
        if [[ "$prefix" == */ ]]; then
            [[ "$f" == "$prefix"* ]] || continue
        else
            [[ "$f" == "$prefix" ]] || continue
        fi
        file_to_generator["$f"]="${FASTFORWARD_GENERATORS[$prefix]}"
        needed_generators["${FASTFORWARD_GENERATORS[$prefix]}"]=1
        matched=1
        echo "  ✓ $f -- covered by: ${FASTFORWARD_GENERATORS[$prefix]}"
        break
    done
    if [[ "$matched" -eq 0 ]]; then
        echo "  ✗ $f -- NOT covered by any registered generator." >&2
        echo "ERROR: not every changed file is a known mechanically-regenerated fixture. Run the full review." >&2
        exit 1
    fi
done <<< "$changed_files"

if [[ ${#needed_generators[@]} -eq 0 ]]; then
    echo "ERROR: no generators to run (unexpected -- changed files matched but registry is empty). Run the full review." >&2
    exit 1
fi

# Restore-on-failure: undo both tracked-file modifications (checkout) and any
# untracked byproducts a generator left behind (clean). Safe to run
# unconditionally -- the dirty-tree precondition above already proved zero
# untracked files existed before this script touched anything, so anything
# `git clean` removes here was created by this run, never pre-existing work.
restore_tree() {
    git checkout -- . 2>/dev/null || true
    # Repo-wide, not scoped to the matched files: a generator's untracked
    # byproduct can land at any path (e.g. a sibling file, not just the file
    # it was registered for), and scoping the pathspec to only the matched
    # files misses exactly that case. Unscoped is safe here specifically
    # because of the guarantee above -- there is nothing else it could delete.
    git clean -fd 2>/dev/null || true
}

# Per-file provenance proof: a generator "covering" a file by path prefix is
# not evidence it actually WRITES that file (e.g. a directory-prefix generator
# with a hardcoded internal file list may silently skip files added after the
# list was last updated). Prove coverage for real: delete each matched file so
# the committed content can no longer coincidentally equal the pre-run state,
# run its generator, then require the file to reappear byte-for-byte. A file
# the generator doesn't actually own stays missing/wrong and is caught here --
# checking overall `git status` cleanliness alone (the prior design) cannot
# distinguish "generator produced this" from "generator never touched this."
echo ""
echo "Deleting ${#file_to_generator[@]} changed file(s) to prove their generator actually reproduces them:"
for f in "${!file_to_generator[@]}"; do
    echo "  - $f"
    rm -f -- "$f"
done

echo ""
echo "Re-running ${#needed_generators[@]} generator(s):"
for gen in "${!needed_generators[@]}"; do
    echo "  \$ $gen"
    if ! bash -c "$gen"; then
        echo "ERROR: generator failed to run ('$gen'). Run the full review." >&2
        restore_tree
        exit 1
    fi
done

echo ""
echo "Verifying each deleted file was restored byte-for-byte by its generator:"
for f in "${!file_to_generator[@]}"; do
    if [[ ! -e "$f" ]]; then
        echo "  ✗ $f -- generator did NOT recreate this file." >&2
        echo "ERROR: '${file_to_generator[$f]}' does not actually reproduce $f -- registry entry is wrong or stale. Refusing to fast-forward." >&2
        restore_tree
        exit 1
    fi
    if ! git diff --quiet HEAD -- "$f" 2>/dev/null; then
        echo "  ✗ $f -- regenerated content differs from what's committed." >&2
        echo "ERROR: re-running the generator produced DIFFERENT content for $f than what's committed. Refusing to fast-forward. Run the full review." >&2
        restore_tree
        exit 1
    fi
    echo "  ✓ $f -- byte-for-byte match."
done

# Whole-tree check catches anything the generators touched OUTSIDE the
# expected file set (unrelated drift, stray output) -- a clean per-file
# verification above is necessary but not sufficient if a generator has wider
# side effects than the registry entry implies.
post_diff="$(git status --porcelain 2>/dev/null)"
if [[ -n "$post_diff" ]]; then
    echo ""
    echo "ERROR: generator(s) touched file(s) outside the expected changed-file set:" >&2
    echo "$post_diff" >&2
    echo "Refusing to fast-forward -- unexpected side effects are not provably safe. Run the full review." >&2
    restore_tree
    exit 1
fi

echo ""
echo "✓ All ${#file_to_generator[@]} file(s) proven byte-for-byte reproducible by their registered generator(s)."

# Re-stamp: SAME field count as the original (the code-review sentinel's
# 5th field, min-score=N, is optional -- 4 or 5 fields both validate; the
# PHR sentinel always has 5). Preserve whichever shape was already there
# rather than assuming 5, so a 4-field original doesn't get a corrupt empty
# 5th field appended. SHA + timestamp updated, verdict/min-score carried
# over unchanged. No new field -- nothing for the pre-push field-count
# validators to reject.
new_ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
if [[ -n "$sen_min" ]]; then
    printf 'v1|%s|%s|%s|%s\n' "$head_sha" "$sen_verdict" "$new_ts" "$sen_min" > "$SENTINEL"
else
    printf 'v1|%s|%s|%s\n' "$head_sha" "$sen_verdict" "$new_ts" > "$SENTINEL"
fi

mkdir -p "$(dirname "$FASTFORWARD_LOG")"
printf '%s fast-forward %s: %s -> %s (generators: %s)\n' \
    "$new_ts" "$(basename "$SENTINEL")" "$sen_sha" "$head_sha" \
    "$(printf '%s; ' "${!needed_generators[@]}")" >> "$FASTFORWARD_LOG"

echo "✓ $(basename "$SENTINEL") fast-forwarded: ${sen_sha:0:8} -> ${head_sha:0:8} (logged to $(basename "$(dirname "$FASTFORWARD_LOG")")/$(basename "$FASTFORWARD_LOG"))"
exit 0
